### ISSUE TITLE
No mod commands implemented yet

### ISSUE THREAD

**Issue by VaronBros** [RiiConnect24/RC24-Bot#50]
So what are you going to use for mod commands? I found a lib for JDA mod commands, or maybe Artuto can help

**Comment by spotlightishere** [comment]
Wew, assignments are really annoying.

Moderation commands aren't implemented because they're not the purpose of the bot anymore. Even the bot's primary community doesn't need it: 
![screenshot_20171025-110725](https://user-images.githubusercontent.com/10055256/32009497-ec73f60a-b974-11e7-9c20-7bbca6c1be1a.png)

**Comment by KcrPL** [comment]
>Wew, assignments are really annoying.

Really? XD @spotlightishere

**Comment by spotlightishere** [comment]
Yes, it's an extra email for everyone subscribed and anyone else can answer the same. xP

**Comment by VaronBros** [comment]
olol
